name: Meterian Scanner workflow

on:
  push:
    branches: [master, ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]
  schedule:
    - cron: '0 6 * * 3'

jobs:
  meterian_scan:
    name: Meterian client scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Meterian Scanner
        uses: MeterianHQ/meterian-github-action@v1.0.3
        env:
          METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
